name: cassandart
description: 'Cassandra database client (driver wire protocol: v4, CQL: 3.0).'
version: 0.4.0
homepage: https://github.com/isoos/cassandart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  buffer: ^1.1.1
  meta: ^1.7.0
  page: ^1.2.0

dev_dependencies:
  test: ^1.19.2
  lints: ^1.0.1
  http: ^0.13.4
