name: cassandart
description: 'Cassandra database client (driver wire protocol: v4, CQL: 3.0).'
version: 0.2.0
homepage: https://github.com/isoos/cassandart
author: Istvan Soos <istvan.soos@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  buffer: ^1.0.0
  meta: ^1.0.0
  page: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
